site_name: Nicholas Decheine Website
repo_url: https://decheine.github.io/decheine-site
site_dir: public

nav:
  - Home: index.md

markdown_extensions:
  - abbr
  - fenced_code
  - meta
  - admonition
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  #- pymdownx.emoji:
  #    emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - toc:
      permalink: true
      toc_depth: 6

plugins:
  - search
  - pdf-export:
      enabled_if_env: ENABLE_MKDOCS_PDF #export ENABLE_MKDOCS_PDF=1 if want to generate PDF
      combined: true # combine all pages into single PDF
      combined_output_path: pdf/websitePage.pdf

theme: material

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
